# Generated by Django 2.0.7 on 2018-07-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chpice',
            new_name='Choice',
        ),
    ]
